// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyABQtJGis_5Rcxlm3WKO5ahJJ-M1VFGZ78',
    appId: '1:1072419323384:web:d981f7f38676b3e4daaa0d',
    messagingSenderId: '1072419323384',
    projectId: 'portfolio-71c4d',
    authDomain: 'portfolio-71c4d.firebaseapp.com',
    storageBucket: 'portfolio-71c4d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD23YvmehfwNjPbkc1fDI91_78gy2Ms-Ho',
    appId: '1:1072419323384:android:46d43fcf4481edf8daaa0d',
    messagingSenderId: '1072419323384',
    projectId: 'portfolio-71c4d',
    storageBucket: 'portfolio-71c4d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8UtH5pRGJuQOoIOOTevB_Cas_vvv8ie4',
    appId: '1:1072419323384:ios:c5efbbb05eb308c9daaa0d',
    messagingSenderId: '1072419323384',
    projectId: 'portfolio-71c4d',
    storageBucket: 'portfolio-71c4d.firebasestorage.app',
    iosBundleId: 'com.example.mywebsite',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD8UtH5pRGJuQOoIOOTevB_Cas_vvv8ie4',
    appId: '1:1072419323384:ios:c5efbbb05eb308c9daaa0d',
    messagingSenderId: '1072419323384',
    projectId: 'portfolio-71c4d',
    storageBucket: 'portfolio-71c4d.firebasestorage.app',
    iosBundleId: 'com.example.mywebsite',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyABQtJGis_5Rcxlm3WKO5ahJJ-M1VFGZ78',
    appId: '1:1072419323384:web:55a28ee79358961bdaaa0d',
    messagingSenderId: '1072419323384',
    projectId: 'portfolio-71c4d',
    authDomain: 'portfolio-71c4d.firebaseapp.com',
    storageBucket: 'portfolio-71c4d.firebasestorage.app',
  );
}
